[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
noLigation = true

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss08"

    [buildPlans.IosevkaCustom.variants.design]
    seven = "curly-serifed-crossbar"
    h = "tailed-serifed"
    l = "serifed-semi-tailed"
    m = "short-leg-tailed-serifed"
    n = "tailed-serifed"
    u = "toothless-rounded-serifed"
    brace = "curly"

    [buildPlans.IosevkaCustom.variants.italic]
    seven = "curly-serifed-crossbar"
    a = "single-storey-serifed"
    f = "tailed"
    s = "unilateral-serifed"
    z = "curly-top-serifed"
    brace = "curly"
