[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true
noLigation = false

  [buildPlans.IosevkaCustom.widths.Normal]
  shape = 548
  menu = 5
  css = "normal"

  [buildPlans.IosevkaCustom.weights.regular]
  shape = 425
  menu = 400
  css = 400

  [buildPlans.IosevkaCustom.weights.semibold]
  shape = 600
  menu = 600
  css = 600

  [buildPlans.IosevkaCustom.weights.bold]
  shape = 700
  menu = 700
  css = 700

  [buildPlans.IosevkaCustom.metricOverride]
  xHeight = 550

  [buildPlans.IosevkaCustom.ligations]
  enables = [
    "arrow-l",
    "arrow-r",
    "arrow-lr",
    "trig",
    "ltgt-diamond-tag",
    "ltgt-slash-tag",
    "slash-asterisk",
    "html-comment"
  ]

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss08"

    [buildPlans.IosevkaCustom.variants.design]
    two = "straight-neck-serifless"
    three = "flat-top-serifless"
    four = "semi-open-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    seven = "curly-serifless-crossbar"
    nine = "straight-bar"
    zero = "tall-slashed-cutout"
    l = "serifed-semi-tailed"
    m = "short-leg-serifless"
    u = "toothless-rounded-serifless"
    tittle = "square"
    diacritic-dot = "square"
    punctuation-dot = "square"
    underscore = "above-baseline"
    caret = "low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    dollar = "through"
    percent = "rings-continuous-slash"

    [buildPlans.IosevkaCustom.variants.italic]
    a = "single-storey-tailed"
    e = "rounded"
    i = "tailed-serifed"
    f = "tailed"

[buildPlans.IosevkaSlabCustom]
family = "Iosevka Slab Custom"
spacing = "term"
serifs = "slab"
noCvSs = true
exportGlyphNames = true
noLigation = false

weights.inherits = "buildPlans.IosevkaCustom"
widths.inherits = "buildPlans.IosevkaCustom"

  [buildPlans.IosevkaSlabCustom.metricOverride]
  xHeight = 550

  [buildPlans.IosevkaSlabCustom.ligations]
  enables = [
    "arrow-l",
    "arrow-r",
    "arrow-lr",
    "trig",
    "ltgt-diamond-tag",
    "ltgt-slash-tag",
    "slash-asterisk",
    "html-comment"
  ]

  [buildPlans.IosevkaSlabCustom.variants]
  inherits = "ss08"

    [buildPlans.IosevkaSlabCustom.variants.design]
    two = "straight-neck-serifed"
    three = "flat-top-serifed"
    four = "semi-open-serifed"
    five = "oblique-flat-serifed"
    six = "straight-bar"
    seven = "curly-serifed-crossbar"
    nine = "straight-bar"
    zero = "tall-slashed-cutout"
    l = "serifed-semi-tailed"
    m = "short-leg-serifed"
    u = "toothless-rounded-serifed"
    tittle = "square"
    diacritic-dot = "square"
    punctuation-dot = "square"
    underscore = "above-baseline"
    caret = "low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    dollar = "through"
    percent = "rings-continuous-slash"

    [buildPlans.IosevkaSlabCustom.variants.italic]
    a = "single-storey-tailed"
    e = "rounded"
    i = "tailed-serifed"
    f = "tailed"
    p = "eared-motion-serifed"
    q = "straight-serifless"
    s = "unilateral-serifed"
    u = "toothless-rounded-motion-serifed"
    z = "curly-top-serifed"
