[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
noLigation = true

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss08"

    [buildPlans.IosevkaCustom.variants.design]
    two = "straight-neck-serifed"
    three = "flat-top-serifed"
    four = "semi-open-serifed"
    five = "oblique-flat-serifed"
    six = "straight-bar"
    seven = "curly-serifed-crossbar"
    nine = "straight-bar"
    zero = "tall-slashed-cutout"
    l = "serifed-semi-tailed"
    m = "short-leg-serifed"
    u = "toothless-rounded-serifed"
    underscore = "above-baseline"
    caret = "low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    dollar = "through"
    percent = "rings-continuous-slash"

    [buildPlans.IosevkaCustom.variants.italic]
    a = "single-storey-serifed"
    f = "tailed"
    s = "unilateral-serifed"
    z = "curly-top-serifed"
